export const figmaAssets = {
  imgVector: "/Button/chevron-left.png",
  imgVector1: "/Button/chevron-right.png",
  imgVector3: "/Cell/Vector-3.png",
  imgVector4: "/search.png",
  imgVector5: "/Cell/Checkbox.png",
  imgVector6: "/direction.png",
  imgVector7: "/help-1.png",
  imgVector8: "/Cell/Button/Vector-1.png",
  imgVector9: "/list.png",
  imgVector10: "/help.png",
  imgVector11: "/settings.png",
  imgVector12: "/user-prod.png",
  imgVector13: "/bell.png",
  imgVector14: "/key.png",
  imgDesign: "/Logo%20Dealfront.png",
  logoLeadfeederSmall: "/Cell/Logo/Cell/Leadfeeder%20Small.svg",
  logoPromote: "/Cell/Logo/Product/Promote/icon.svg",
  logoTarget: "/Cell/Logo/Product/Target/icon.svg",
  logoWebVisitors: "/Cell/Logo/Product/WebVisitors/icon.svg",
  logoConnect: "/Cell/Logo/Product/Connect/icon.svg",
  logoProspector: "/Cell/Logo/Product/Prospector/icon.svg",
  logoLists: "/Cell/Logo/Product/Lists/icon.svg",
};
